name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install python-dotenv  # if not already in requirements.txt

    - name: Load Environment Variables
      run: |
        echo "Loading environment variables from .env"
        python -m dotenv set -q $(cat .env | xargs)

    - name: Set up Database
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        python manage.py migrate
        python manage.py collectstatic --noinput

    - name: Run Tests
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        python manage.py test
